//
//  ShowSongWorker.swift
//  cooltunes
//
//  Created by Luis Zapata on 10/6/19.
//  Copyright (c) 2019 Luis Zapata. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class ShowSongWorker
{
    func requestAlbumSongs(collectionId: Int, completion: @escaping (ShowSong.AlbumSongs.Response?, Error?) -> ()){
        let fullResource = "/lookup?id=" + String(collectionId) + "&entity=song"
        requestHandler.get(resource: fullResource).validate().responseJSON { response in
            switch response.result {
            case .success(_):
                do {
                    let parsedResponse = try JSONDecoder().decode(ShowSong.AlbumSongs.Response.self, from: response.data!)
                    completion(parsedResponse,nil)
                } catch let err {
                    completion(nil,err)
                }
            case .failure(let err):
                completion(nil,err)
            }
            
        }
    }
}
