//
//  ShowSongModels.swift
//  cooltunes
//
//  Created by Luis Zapata on 10/6/19.
//  Copyright (c) 2019 Luis Zapata. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ShowSong
{    
    enum AlbumSongs
    {
        struct Request
        {
        }
        struct Response: Decodable {
            var resultCount: Int
            var results: [Song]?
        }
        struct ViewModel
        {
            struct DisplayedSongs
            {
                var trackNumber: Int?
                var trackName: String?
            }
            var displayedSongs: [DisplayedSongs]
        }
    }
}
