//
//  ShowSongInteractor.swift
//  cooltunes
//
//  Created by Luis Zapata on 10/6/19.
//  Copyright (c) 2019 Luis Zapata. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ShowSongBusinessLogic
{
    func getSong()
    func requestAlbumSongs()
}

protocol ShowSongDataStore
{
    var song: Song? { get set }
    var albumSongs: [Song]? { get set }
}

class ShowSongInteractor: ShowSongBusinessLogic, ShowSongDataStore
{
    var presenter: ShowSongPresentationLogic?
    var worker: ShowSongWorker?
    var song: Song?
    var albumSongs: [Song]?
    
    func requestAlbumSongs() {
        if self.song?.collectionId != nil {
            worker = ShowSongWorker()
            worker?.requestAlbumSongs(collectionId: (self.song?.collectionId)!) { (response, error) -> Void in
                if response != nil {
                    self.albumSongs = response?.results
                    self.presenter?.presentAlbumSongs(response: response!)
                } else {
                    print(error as Any)
                }
            }
        }
    }
    
    func getSong() {
        presenter?.presentSong(song: self.song)
    }
}
