//
//  ShowSongPresenter.swift
//  cooltunes
//
//  Created by Luis Zapata on 10/6/19.
//  Copyright (c) 2019 Luis Zapata. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ShowSongPresentationLogic
{
    func presentSong(song: Song?)
    func presentAlbumSongs(response: ShowSong.AlbumSongs.Response)
}

class ShowSongPresenter: ShowSongPresentationLogic
{
    weak var viewController: ShowSongDisplayLogic?
        
    func presentSong(song: Song?) {
        viewController?.displaySong(song: song)
    }
    
    func presentAlbumSongs(response: ShowSong.AlbumSongs.Response) {
        var displayedAlbumSongs: [ShowSong.AlbumSongs.ViewModel.DisplayedSongs] = []
        for song in response.results! {
            if song.wrapperType == "track" {
                let displayedAlbumSong = ShowSong.AlbumSongs.ViewModel.DisplayedSongs.init(trackNumber: song.trackNumber, trackName: song.trackName ?? "")
                displayedAlbumSongs.append(displayedAlbumSong)
            }
        }
        let viewModel = ShowSong.AlbumSongs.ViewModel(displayedSongs: displayedAlbumSongs)
        viewController?.displayAlbumSongs(viewModel: viewModel)
    }
}
