//
//  ListSongsInteractor.swift
//  cooltunes
//
//  Created by Luis Zapata on 10/5/19.
//  Copyright (c) 2019 Luis Zapata. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListSongsBusinessLogic
{
    func search(term: String)
}

protocol ListSongsDataStore
{
    var songs: [Song]? { get set }
}

class ListSongsInteractor: ListSongsBusinessLogic, ListSongsDataStore
{
    
    var presenter: ListSongsPresentationLogic?
    var worker: ListSongsWorker?
    var songs: [Song]?
    
    func search(term: String)
    {
        worker = ListSongsWorker()
        worker?.search(term: term) { (response, error) -> Void in
            if response != nil {
                self.songs = response?.results
                self.presenter?.presentResult(response: response!)
            } else {
                print(error as Any)
            }
        }
    }
}
