//
//  ListSongsPresenter.swift
//  cooltunes
//
//  Created by Luis Zapata on 10/5/19.
//  Copyright (c) 2019 Luis Zapata. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListSongsPresentationLogic
{
    func presentSomething(response: ListSongs.Something.Response)
}

class ListSongsPresenter: ListSongsPresentationLogic
{
    weak var viewController: ListSongsDisplayLogic?
    
    // MARK: Do something
    
    func presentSomething(response: ListSongs.Something.Response)
    {
        let viewModel = ListSongs.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
