//
//  ListSongsInteractor.swift
//  cooltunes
//
//  Created by Luis Zapata on 10/5/19.
//  Copyright (c) 2019 Luis Zapata. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListSongsBusinessLogic
{
    func doSomething(request: ListSongs.Something.Request)
}

protocol ListSongsDataStore
{
    //var name: String { get set }
}

class ListSongsInteractor: ListSongsBusinessLogic, ListSongsDataStore
{
    var presenter: ListSongsPresentationLogic?
    var worker: ListSongsWorker?
    //var name: String = ""
    
    // MARK: Do something
    
    func doSomething(request: ListSongs.Something.Request)
    {
        worker = ListSongsWorker()
        worker?.doSomeWork()
        
        let response = ListSongs.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
